/*
# Gula Feedback — Satisfaction Survey + Prize Roulette + Lead Capture

1. New Tables
   - `feedback_questions`: survey questions created by the admin.
     Supports single-choice (radio), multiple-choice (checkbox), and
     free-text (dissertative) types. Questions are ordered and can be
     active/inactive.
   - `feedback_prizes`: prizes for the roulette wheel. Each prize has a
     name, weight (probability), stock limit, and active flag.
   - `feedback_responses`: individual survey answers submitted by
     customers. One row per question answered, linked to a response
     session (uuid) so all answers from one survey stay grouped.
   - `feedback_leads`: customer leads captured after the survey. Stores
     name, phone, email, birthday, opt-in consent, and links to the
     restaurant.
   - `feedback_vouchers`: prize vouchers generated by the roulette.
     Each has a unique code, linked prize, linked lead, expiry date,
     and a `redeemed_at` timestamp for fraud prevention.

2. Settings
   - `restaurant_settings.feedback_voucher_validity_days` (int, default 30):
     default number of days a voucher is valid after generation.
   - `restaurant_settings.feedback_enabled` (bool, default false):
     master toggle for the feedback module.

3. Security
   - All tables have RLS enabled.
   - Customer-facing tables (questions, prizes, responses, leads,
     vouchers) allow anon + authenticated CRUD where appropriate:
     * questions/prizes: anon can SELECT active rows only (admin
       manages via authenticated).
     * responses/leads/vouchers: anon can INSERT (customer submits
       survey/lead/claims voucher); authenticated has full CRUD.
   - Voucher redemption (UPDATE redeemed_at) is restricted to
     authenticated (restaurant staff) only — anon cannot self-redeem.

4. Notes
   - All tables are multi-tenant via `restaurant_id` nullable column,
     consistent with existing project pattern.
   - Voucher codes use a 6-character alphanumeric uppercase format.
*/

-- ── feedback_questions ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feedback_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id uuid REFERENCES restaurants(id) ON DELETE CASCADE,
  question_text text NOT NULL,
  question_type text NOT NULL DEFAULT 'single' CHECK (question_type IN ('single', 'multiple', 'text')),
  options text[] DEFAULT '{}',
  is_required boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE feedback_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_active_feedback_questions" ON feedback_questions;
CREATE POLICY "anon_select_active_feedback_questions" ON feedback_questions
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "auth_insert_feedback_questions" ON feedback_questions;
CREATE POLICY "auth_insert_feedback_questions" ON feedback_questions
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "auth_update_feedback_questions" ON feedback_questions;
CREATE POLICY "auth_update_feedback_questions" ON feedback_questions
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_delete_feedback_questions" ON feedback_questions;
CREATE POLICY "auth_delete_feedback_questions" ON feedback_questions
  FOR DELETE TO authenticated USING (true);

-- ── feedback_prizes ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feedback_prizes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id uuid REFERENCES restaurants(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  weight int NOT NULL DEFAULT 1 CHECK (weight >= 0),
  stock_limit int, -- null = unlimited
  stock_used int NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE feedback_prizes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_active_feedback_prizes" ON feedback_prizes;
CREATE POLICY "anon_select_active_feedback_prizes" ON feedback_prizes
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "auth_insert_feedback_prizes" ON feedback_prizes;
CREATE POLICY "auth_insert_feedback_prizes" ON feedback_prizes
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "auth_update_feedback_prizes" ON feedback_prizes;
CREATE POLICY "auth_update_feedback_prizes" ON feedback_prizes
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_delete_feedback_prizes" ON feedback_prizes;
CREATE POLICY "auth_delete_feedback_prizes" ON feedback_prizes
  FOR DELETE TO authenticated USING (true);

-- ── feedback_responses ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feedback_responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id uuid REFERENCES restaurants(id) ON DELETE CASCADE,
  session_id uuid NOT NULL DEFAULT gen_random_uuid(),
  question_id uuid NOT NULL REFERENCES feedback_questions(id) ON DELETE CASCADE,
  answer jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE feedback_responses ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_feedback_responses_session ON feedback_responses(session_id);
CREATE INDEX IF NOT EXISTS idx_feedback_responses_restaurant ON feedback_responses(restaurant_id);

DROP POLICY IF EXISTS "anon_insert_feedback_responses" ON feedback_responses;
CREATE POLICY "anon_insert_feedback_responses" ON feedback_responses
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "auth_select_feedback_responses" ON feedback_responses;
CREATE POLICY "auth_select_feedback_responses" ON feedback_responses
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_update_feedback_responses" ON feedback_responses;
CREATE POLICY "auth_update_feedback_responses" ON feedback_responses
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_delete_feedback_responses" ON feedback_responses;
CREATE POLICY "auth_delete_feedback_responses" ON feedback_responses
  FOR DELETE TO authenticated USING (true);

-- ── feedback_leads ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feedback_leads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id uuid REFERENCES restaurants(id) ON DELETE CASCADE,
  session_id uuid,
  name text NOT NULL,
  phone text,
  email text,
  birthday date,
  opt_in boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE feedback_leads ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_feedback_leads_restaurant ON feedback_leads(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_feedback_leads_phone ON feedback_leads(phone);

DROP POLICY IF EXISTS "anon_insert_feedback_leads" ON feedback_leads;
CREATE POLICY "anon_insert_feedback_leads" ON feedback_leads
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "auth_select_feedback_leads" ON feedback_leads;
CREATE POLICY "auth_select_feedback_leads" ON feedback_leads
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "auth_update_feedback_leads" ON feedback_leads;
CREATE POLICY "auth_update_feedback_leads" ON feedback_leads
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_delete_feedback_leads" ON feedback_leads;
CREATE POLICY "auth_delete_feedback_leads" ON feedback_leads
  FOR DELETE TO authenticated USING (true);

-- ── feedback_vouchers ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feedback_vouchers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id uuid REFERENCES restaurants(id) ON DELETE CASCADE,
  lead_id uuid REFERENCES feedback_leads(id) ON DELETE SET NULL,
  prize_id uuid REFERENCES feedback_prizes(id) ON DELETE SET NULL,
  code text NOT NULL,
  customer_name text,
  prize_name text NOT NULL,
  expires_at timestamptz NOT NULL,
  redeemed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE feedback_vouchers ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS idx_feedback_vouchers_code ON feedback_vouchers(code);
CREATE INDEX IF NOT EXISTS idx_feedback_vouchers_restaurant ON feedback_vouchers(restaurant_id);

DROP POLICY IF EXISTS "anon_insert_feedback_vouchers" ON feedback_vouchers;
CREATE POLICY "anon_insert_feedback_vouchers" ON feedback_vouchers
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_select_feedback_vouchers" ON feedback_vouchers;
CREATE POLICY "anon_select_feedback_vouchers" ON feedback_vouchers
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "auth_update_feedback_vouchers" ON feedback_vouchers;
CREATE POLICY "auth_update_feedback_vouchers" ON feedback_vouchers
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_delete_feedback_vouchers" ON feedback_vouchers;
CREATE POLICY "auth_delete_feedback_vouchers" ON feedback_vouchers
  FOR DELETE TO authenticated USING (true);

-- ── Settings columns ──────────────────────────────────────────────────
ALTER TABLE restaurant_settings
  ADD COLUMN IF NOT EXISTS feedback_enabled boolean DEFAULT false;

ALTER TABLE restaurant_settings
  ADD COLUMN IF NOT EXISTS feedback_voucher_validity_days int DEFAULT 30;

-- ── Function to generate unique voucher code ──────────────────────────
CREATE OR REPLACE FUNCTION public.generate_voucher_code()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  code text;
  attempts int := 0;
BEGIN
  LOOP
    code := '';
    FOR i IN 1..6 LOOP
      code := code || substr(chars, floor(random() * length(chars))::int + 1, 1);
    END LOOP;
    EXIT WHEN NOT EXISTS (SELECT 1 FROM feedback_vouchers WHERE code = code);
    attempts := attempts + 1;
    IF attempts > 10 THEN
      code := code || floor(random() * 1000)::text;
      EXIT;
    END IF;
  END LOOP;
  RETURN code;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.generate_voucher_code() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_voucher_code() FROM anon;
